[tool.poetry]
name = "datagun"
version = "0.1.0"
description = ""
authors = ["Charlie Bini <cbini87@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^0.19.0"
SQLAlchemy = "^1.4.25"
pandas = "^1.4.0"
pymssql = "^2.2.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
